package com.coderbd.inventory.view;

import com.coderbd.inventory.domain.ItemsEligibleForOder;
import com.coderbd.inventory.domain.StockSummary;
import com.coderbd.inventory.service.ItemsEligibleForOderService;
import com.coderbd.inventory.service.StockSummaryService;
import com.coderbd.mobile.common.CommonMenu;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rajaul Islam
 */
public final class OrderItemsListStatusForm extends javax.swing.JFrame {

    /**
     * Creates new form StockSummaryForm
     */
    public OrderItemsListStatusForm() {
        initComponents();
        setJMenuBar(CommonMenu.displayMenu(this));
        // displayProductDataWithinTable();
        //displayOdersByStatusWithinTable("Pending");
    }

    public void displayProductDataWithinTable() {
        List<ItemsEligibleForOder> eligibleOrderList = new ArrayList();

        StockSummaryService productService = new StockSummaryService();
        List<StockSummary> pList = productService.getListForOrdersWhenStockLow(210);
        for (StockSummary s : pList) {
            ItemsEligibleForOder item = new ItemsEligibleForOder(s.getId(), s.getProductName(), s.getProductCode(), s.getPurchaseQty(), s.getSoldQty(), s.getAvilableQty(), 0, "pending");
            eligibleOrderList.add(item);
        }

        DefaultTableModel model = (DefaultTableModel) tblDisplayStockSummary.getModel();
        Object[] row = new Object[7];

        for (int i = 0; i < eligibleOrderList.size(); i++) {
            row[0] = eligibleOrderList.get(i).getId();
            row[1] = eligibleOrderList.get(i).getProductName();
            row[2] = eligibleOrderList.get(i).getProductCode();
            row[3] = eligibleOrderList.get(i).getPurchaseQty();
            row[4] = eligibleOrderList.get(i).getSoldQty();
            row[5] = eligibleOrderList.get(i).getAvilableQty();
            row[6] = eligibleOrderList.get(i).getOrderQty();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayStockSummary = new javax.swing.JTable();
        cmbOrderstatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnChangeOrderStatus = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Eligible Items By Ordear Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tblDisplayStockSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Item Code", "Qty In", "Qty Out", "Available Qty", "Order Qty", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDisplayStockSummary);

        cmbOrderstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Order Status", "Pending", "Under Process", "Cancel", "Confirmed" }));
        cmbOrderstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOrderstatusItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Order Status");

        btnChangeOrderStatus.setText("Update Status");
        btnChangeOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeOrderStatusActionPerformed(evt);
            }
        });

        jTextField1.setText("Confirmed");

        jTextField2.setText("Cancel");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Under Process");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbOrderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(btnChangeOrderStatus)
                .addGap(488, 488, 488))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeOrderStatus)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrderstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOrderstatusItemStateChanged
        String item = cmbOrderstatus.getItemAt(cmbOrderstatus.getSelectedIndex());
        //  String ids = item.split(",")[0];
        System.out.println("reza item ::::::::: " + item);
        refreshTable();
        displayOdersByStatusWithinTable(item);
    }//GEN-LAST:event_cmbOrderstatusItemStateChanged

    private void btnChangeOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeOrderStatusActionPerformed
        ItemsEligibleForOderService orderService = new ItemsEligibleForOderService();

        //table 
        DefaultTableModel model = (DefaultTableModel) tblDisplayStockSummary.getModel();
        Vector data = model.getDataVector();
        Set<ItemsEligibleForOder> colData;
        Vector row = null;
        ItemsEligibleForOder item = null;
        for (int i = 0; i < tblDisplayStockSummary.getRowCount(); i++) {
            colData = new HashSet(tblDisplayStockSummary.getRowCount());
            row = (Vector) data.elementAt(i);
            String s = row.get(6).toString();

            item = new ItemsEligibleForOder(Integer.parseInt(s), row.get(7).toString());
            item.setId(Integer.parseInt(row.get(0).toString()));
            colData.add(item);
            ItemsEligibleForOderService itemsservice = new ItemsEligibleForOderService();
            System.out.println("size of colData: " + colData.size());

            itemsservice.updateList(colData);
/*
            //Update it to product Purchase field
            StockSummaryService pss = new StockSummaryService();

            try {

                if (row.get(7).toString().equals("Confirmed")) {
                    StockSummary bs = pss.getProductSummaryByProductCode(row.get(2).toString());
// data from db
                    // after modification
                    int nowPurchaseQty = bs.getPurchaseQty() + item.getOrderQty();
                    int nowAvailableQty = bs.getAvilableQty() + item.getOrderQty();

                    StockSummary bsx = new StockSummary(nowPurchaseQty, nowAvailableQty);
                    bsx.setId(bs.getId());

                    pss.updateWhenOrderConfirmed(bsx);

                }

            } catch (Exception e) {
                System.out.println("No Confirmed Status for update Stock Summary");
            }
*/
        }
    }//GEN-LAST:event_btnChangeOrderStatusActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblDisplayStockSummary.getModel();
        model.setRowCount(0);

    }

    public void displayOdersByStatusWithinTable(String orderStatus) {

        ItemsEligibleForOderService os = new ItemsEligibleForOderService();
        List<ItemsEligibleForOder> eligibleOrderList = os.getItemsEligibleForOderByOrderStatus(orderStatus);

        DefaultTableModel model = (DefaultTableModel) tblDisplayStockSummary.getModel();
        Object[] row = new Object[8];

        for (int i = 0; i < eligibleOrderList.size(); i++) {
            row[0] = eligibleOrderList.get(i).getId();
            row[1] = eligibleOrderList.get(i).getProductName();
            row[2] = eligibleOrderList.get(i).getProductCode();
            row[3] = eligibleOrderList.get(i).getPurchaseQty();
            row[4] = eligibleOrderList.get(i).getSoldQty();
            row[5] = eligibleOrderList.get(i).getAvilableQty();
            row[6] = eligibleOrderList.get(i).getOrderQty();
            row[7] = eligibleOrderList.get(i).getOrderStatus();

            model.addRow(row);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderItemsListStatusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderItemsListStatusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderItemsListStatusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderItemsListStatusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderItemsListStatusForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeOrderStatus;
    private javax.swing.JComboBox<String> cmbOrderstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblDisplayStockSummary;
    // End of variables declaration//GEN-END:variables
}
